# Server configuration
server.port=8080

# Database configurations (H2 database)
spring.datasource.url=jdbc:h2:mem:authrbacdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false
# Required to access H2 console frames in Spring Security
spring.h2.console.settings.trace=false

# Hibernate configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT configurations
# Base64 encoded HMAC-SHA256 Secret (256-bit key)
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Expiration: 1 day in milliseconds (86400000 ms)
app.jwt.expiration-ms=86400000

# Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
